### ISSUE TITLE
[BUG] Plugin not loading 

### ISSUE THREAD

**Issue by KittenPixel-cell** [Exiled-Team/Common-Utils#105]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Plugin loading correctly

**Server logs**
https://pastebin.com/PCXJg3NK

**Copy of current CU config section**
CommonUtilities:
  # Whether or not debug messages should be shown.
  debug: false
  # The SCP Roles able to use V to talk to humans.
  scp_speech:
  - Scp049
  # Whether or not MTF/CI can 'escape' while disarmed to switch teams.
  disarm_switch_teams: true
  # Whether or not disarmed people will be prevented from interacting with >
  restrictive_disarming: true
  # The text displayed at the timed interval specified below.
  timed_broadcast: <color=lime>This server is running </color><color=red>EX>
  # The time each timed broadcast will be displayed.
  timed_broadcast_duration: 5
  # The delay between each timed broadcast. To disable timed broadcasts, se>
  timed_broadcast_delay: 300
  # The message displayed to the player when they first join the server. Se>
  join_message: <color=lime>Welcome %player%! Please read our rules!</color>
  # The amount of time (in seconds) the join message is displayed.
  join_message_duration: 5
# The amount of time (in seconds) after the round starts, before the faci>
  autonuke_time: 1500
  # Wether or not the nuke should be unable to be disabled during the auto->
  autonuke_lock: true
  # The message given to all players when the auto-nuke is triggered. A dur>
  autonuke_broadcast:
    # The broadcast content
    content: The auto nuke has been activated.
    # The broadcast duration
    duration: 10
    # The broadcast type
    type: Normal
    # Indicates whether the broadcast should be shown or not
    show: true
  # Whether or not to show player's health under their name when you look a>
  player_health_info: true
  # Whether or not friendly fire should automatically turn on when a round >
  friendly_fire_on_round_end: true
  # The multiplier applied to radio battery usage. Set to 0 to disable radi>
# The multiplier applied to radio battery usage. Set to 0 to disable radi>
  radio_battery_drain_multiplier: 1
  # The color to use for lights while the warhead is active.
  warhead_color:
    r: 1
    g: 0.2
    b: 0.2
    a: 1
  # The maximum time, in seconds, that a player can be AFK before being kic>
  afk_limit: 120
  # The roles that are ignored by the AFK system.
  afk_ignored_roles:
  - Scp079
  - Spectator
  - Tutorial
  # The list of starting items for roles. ItemName is the item to give them>
  starting_inventories:
    ClassD:
      slot1:
      - item_name: KeycardJanitor

 chance: 10
        group: none
      - item_name: Coin
        chance: 100
        group: none
      slot2:
      - item_name: Flashlight
        chance: 100
        group: none
      slot3: []
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo:
      - type: Ammo556x45
        amount: 200
        group: none
  # The list of custom 914 recipies. Original is the item being upgraded, N>
 scp914_item_changes:
    Rough:
    - original: KeycardO5
      new: MicroHID
      chance: 50
  # The list of custom 914 recipies for roles. Original is the role to be c>
  scp914_class_changes:
    Rough:
    - original: ClassD
      new: Spectator
      chance: 100
      keep_inventory: true
  # The list of 914 teleport settings. Note that if you set "zone" to anyth>
  scp914_teleport_chances:
    Rough:
    - zone: Unspecified
      room: LczClassDSpawn
      offset:
        x: 0
        y: 0
z: 0
      chance: 100
      damage: 250
  # A dictionary of random effects to apply to players when going through 9>
  scp914_effect_chances:
    Rough:
    - effect: AmnesiaVision
      chance: 100
      duration: 0
  # Determines if 914 effects are exclusive, meaning only one can be applie>
  scp914_effects_exclusivity: false
  # Whether or not SCPs are immune to effects gained from 914.
  scps_immune_to914_effects: false
  # The frequency (in seconds) between ragdoll cleanups. Set to 0 to disabl>
  ragdoll_cleanup_delay: 0
  # If ragdoll cleanup should only happen in the Pocket Dimension or not.
  ragdoll_cleanup_only_pocket: false
  # The frequency (in seconds) between item cleanups. Set to 0 to disable.
  item_cleanup_delay: 0
  # If item cleanup should only happen in the Pocket Dimension or not.
 item_cleanup_only_pocket: false
  # A list of all roles and their damage modifiers. The number here is a mu>
  role_damage_multipliers:
    Scp173: 1
  # A list of all Weapons and their damage modifiers. The number here is a >
  damage_multipliers:
    E11Sr: 1
  # A list of roles and how much health they should be given when they kill>
  health_on_kill:
    Scp173: 0
    Scp939: 10
  # A list of roles and what their default starting health should be.
  health_values:
    Scp173: 3200
    NtfCaptain: 120
  # If the plugin is enabled or not.
  is_enabled: true

**EXILED Version:**6.0.0-beta.22
**Plugin Version:**7.0.2

**Results of `show plugins` command in console:**

                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 6.0.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium

**Additional context**

**Comment by KittenPixel-cell** [comment]
fixed on new update

**Comment by louis1706** [comment]
> fixed on new update

can you closed the issue :3
