### ISSUE TITLE
zone_blacklist: Filter unwanted rooms from the zone config in scp914_teleport_chances

### ISSUE THREAD

**Issue by Nefiji** [Exiled-Team/Common-Utils#114]
I think that being able to set a whole zone instead of individual rooms as teleportation destinations is a super useful feature, though its actual usability is suffering by the fact that some zones contain unusable rooms that either place the player into the void (Lcz173) or put them out of bounds irreversibly. (EzCollapsedTunnel) Also there are some rooms that teleport the player one zone closer to surface than intended, i.e. because the teleport point ist set on the other side of the checkpoint/gate.

I think that it would be an extremely helpful addition to the zone config line, if you also could configure a comma-separated list of rooms (zone_blacklist) for each scp914_teleport_chances declaration, with which a server admin can remove certain rooms from the given zone - both for fixing faulty destinations as well as for fine-tuning the balance.

**Comment by Mikihero** [comment]
@Misfiy yet another close
