### ISSUE TITLE
I'm tired of this stupid 914 bug with class changing. WHY THE FUCK DOES IT CLEAR YOUR INVENTORY?!

### ISSUE THREAD

**Issue by ProKameron528999** [Exiled-Team/Common-Utils#122]
https://medal.tv/games/scp-secret-laboratory/clips/1aUEB870FujQfD/d1337RneMf0l?invite=cr-MSxkS0gsMTgzNjc5MDI2LA

Clears your fucking inventory when you change class, but keep_inventory for every class change IS ON...........

**Comment by louis1706** [comment]
you clearly have skill issue in your config they are full configurable in config

**Comment by joker-119** [comment]
cannot replicate
