### ISSUE TITLE
AFKImmunity is broken

### ISSUE THREAD

**Issue by Czekoloczek** [Exiled-Team/Common-Utils#133]
**Describe the bug**
AFKImmunity is not working and the Anti AFK still kicks you

**To Reproduce**
Steps to reproduce the behaviour:
1. Have AFKImmunity permission and be AFK

**Expected behaviour**
The anti AFK shouldn't kick you.

**EXILED Version ("latest" is not a version):**
8.8.1

**Comment by Mikihero** [comment]
works on 13.4.2 with exiled 8.8.1
