### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Sni1ky** [Exiled-Team/Common-Utils#28]
![gsweg](https://user-images.githubusercontent.com/88861006/129278361-0098229f-082e-4a26-9943-e7c1d6ecdcea.PNG)

**Comment by joker-119** [comment]
> Could not load file or assembly Exiled.CustomItems

You need to have Exiled.CustomItems installed, as CommonUtilities's recent update adds missing support for Custom Items to be named in inventory/upgrade configs.
