### ISSUE TITLE
CLASS_NAME to SCP-173 Breaks 914, and does not change your class

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/Common-Utils#36]

**Comment by joker-119** [comment]
I believe this is a base-game bug. Avoid using 173 as a possibility for 914 upgrades. It's known that multiple 183's break the game anyways, so them breaking 914 isn't surprising.

I will still attempt to find a fix but it's priority is lower since it may not be fixable.

**Comment by joker-119** [comment]
This is confirmed to be a Northwood issue, it is also client-side, as only the player turned into 173 is actually affected by the softlock.

This is not a bug we can fix, we will need to wait for Northwood to fix the client-side issue that causes this to occur.
