### ISSUE TITLE
When someone escapes, make the previous items in their inventory before escape teleport right to their feet when they escape 

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/Common-Utils#43]
Example. Scientist escapes with O5, the O5 will spawn below his feet when he changes into an NTF Specialist

**Comment by joker-119** [comment]
It's supposed to do that already

**Comment by JustJesseGITHUB** [comment]
Weird it doesn't for me it just adds the item to the inventory

**Comment by joker-119** [comment]
That's base-game behavior that handles it, I guess they changed it to add to inventory if there's room, talk to NW
