### ISSUE TITLE
You are rude with your users and a totally idiot in your life

### ISSUE THREAD

**Issue by Donnardu** [Exiled-Team/Common-Utils#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured

**EXILED Version ("latest" is not a version):**

**Results of `show plugins` command in console:**

**Additional context**

**Comment by joker-119** [comment]
Someone is a whiney baby
