### ISSUE TITLE
Common utils config deleting itself and not regenerating

### ISSUE THREAD

**Issue by growled** [Exiled-Team/Common-Utils#52]
**Describe the bug**
Common Utilities deleted it's own config

**To Reproduce**
1. Install exiled alpha.80
2. Have a previous config of common utilities
3. Download and use the version 4.1.0
4. Configs get deleted and message displayed is
5. https://cdn.discordapp.com/attachments/656709515936530445/883238153937367050/unknown.png

**Expected behavior**
Common utilities starts up, doesnt delete your old config, or at least tries to say "doesnt have default configs... generating."

**Server logs**
https://pastebin.com/acQV5KJS

**EXILED Version ("latest" is not a version):**
alpha.80

**Results of `show plugins` command in console:**
[2021-09-03 07:37:47.002 +01:00] Total number of plugins: 19
Enabled plugins: 19
Disabled plugins: 0

Buddy:
        - Author: DGvagabond
        - Version: 1.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: buddy
        - Priority: Highest
Exiled.Events:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_events
        - Priority: Highest
ReportPing:
        - Author: Jepp Developments
        - Version: 1.1.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: report_ping
        - Priority: High
Stalky106:
        - Author: RogerFK
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: ST106
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 4.0.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: discord_integration
        - Priority: Medium
Ban Logger:
        - Author: Jesus-QC
        - Version: 1.0.7
        - Required Exiled Version: 3.0.0
        - Prefix: BanLogger
        - Priority: Medium
PlayerList:
        - Author: SrLicht
        - Version: 1.0.6
        - Required Exiled Version: 3.0.0.0
        - Prefix: player_list
        - Priority: Medium
Ultimate AFK:
        - Author: Thomasjosif
        - Version: 3.1.6
        - Required Exiled Version: 3.0.0.0
        - Prefix: uAFK
        - Priority: Medium
Exiled.Updater:
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_updater
        - Priority: Medium
WaitAndChillReborn:
        - Author: Michal78900
        - Version: 3.0.2
        - Required Exiled Version: 3.0.0
        - Prefix: wait_and_chill_reborn
        - Priority: Medium
InfiniteAmmo:
        - Author: InfiniteAmmo
        - Version: 1.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: infinite_ammo
        - Priority: Medium
Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_credits
        - Priority: Medium
RespawnTimer:
        - Author: Michal78900
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: respawn_timer
        - Priority: Medium
Admin Tools:
        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
        - Version: 3.0.3
        - Required Exiled Version: 3.0.0
        - Prefix: AT
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
SerpentsHand:
        - Author: Cyanox, maintained by Michal78900
        - Version: 3.0.2
        - Required Exiled Version: 3.0.0
        - Prefix: serpents_hand
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
Scp096Info:
        - Author: VersLugia
        - Version: 1.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: scp096_info
        - Priority: Low
SCPStats:
        - Author: PintTheDragon
        - Version: 1.4.1
        - Required Exiled Version: 3.0.0
        - Prefix: scp_stats
        - Priority: Lowest

**Additional context**
N/A

**Comment by growled** [comment]
just removed it, ran my server, reinstalled it and added it back and it's generated the default config fine. 

weird.

**Comment by joker-119** [comment]
You had an outdated version of CU.
