### ISSUE TITLE
Ragdoll cleanup delay not working

### ISSUE THREAD

**Issue by Nyxlyzers** [Exiled-Team/Common-Utils#56]
![image](https://user-images.githubusercontent.com/66521547/132108437-cd653640-ca6f-4f6e-a28e-988e5045e850.png)

It's cleaning the corpses instantly, instead of every 120 seconds.

**Comment by joker-119** [comment]
1. Please use the bug report template when reporting bugs.
2. The ragdoll cleanup is done in a loop that repeats every x seconds, where x is the value you enter in this config. It's not a timer for each individual ragdoll as that would be an extremely bad idea, therefore it's possible for a ragdoll to be created a few seconds before the loop's delay is over, and thus get 'immediately' cleaned.
