### ISSUE TITLE
SCP-914 scp can't obtain effects and exclusive effects do not work.

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/Common-Utils#61]
**Bug Consists Of**
SCP-914 exclusive effects do not work.
SCP can't obtain effects does not work

**To Reproduce**
1. Turn two effects to 100% chance on the same SCP-914 mode.
2. Become an SCP and make an effect 100% chance on an SCP-914 mode, then turn scp_can_obtain_effects to false.

**Expected behavior**
Two effects are applied at the same time.

**Server logs**
No server logs due to debug not being on.

**Copy of current CU config section**
   Coarse:
    - effect: Amnesia
      chance: 15
      duration: 30
    - effect: Hemorrhage
      chance: 15
      duration: 30
    - effect: Asphyxiated
      chance: 15
      duration: 15
    - effect: Poisoned
      chance: 15
      duration: 15
    - effect: Bleeding
      chance: 15
      duration: 15
    - effect: Concussed
      chance: 15
      duration: 30
    - effect: Deafened
      chance: 15
      duration: 30
    - effect: Disabled
      chance: 15
      duration: 30
    - effect: Exhausted
      chance: 15
      duration: 30
    - effect: Panic
      chance: 15
      duration: 30
    - effect: Ensnared
      chance: 15
      duration: 15
    Fine:
    - effect: Invisible
      chance: 15
      duration: 15
    - effect: Invigorated
      chance: 15
      duration: 15
    - effect: Visuals939
      chance: 15
      duration: 15
    - effect: Scp207
      chance: 15
      duration: 15
    - effect: Poisoned
      chance: 15
      duration: 15
    - effect: Bleeding
      chance: 15
      duration: 15
    - effect: Hemorrhage
      chance: 15
      duration: 15
    VeryFine:
    - effect: Invisible
      chance: 25
      duration: 15
    - effect: Invigorated
      chance: 25
      duration: 15
    - effect: Visuals939
      chance: 25
      duration: 15
    - effect: Scp207
      chance: 25
      duration: 15
    - effect: Poisoned
      chance: 25
      duration: 15
    - effect: Bleeding
      chance: 25
      duration: 15
    - effect: Hemorrhage
      chance: 25
      duration: 15

**EXILED Version ("latest" is not a version):**
Version 83.

**Results of `show plugins` command in console:**
Enabled plugins: 18
Disabled plugins: 0

Exiled.Events:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_events
        - Priority: Highest
Stalky106:
        - Author: RogerFK
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: ST106
        - Priority: Medium
RespawnTimer:
        - Author: Michal78900
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: respawn_timer
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 4.0.5.0
        - Required Exiled Version: 3.0.0
        - Prefix: discord_integration
        - Priority: Medium
Custom096:
        - Author: Build
        - Version: 1.0.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom096
        - Priority: Medium
Exiled.Updater:
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_updater
        - Priority: Medium
CustomAnnouncements:
        - Author: Build
        - Version: 1.1.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom_announcements
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_credits
        - Priority: Medium
PeanutFckingExplodes:
        - Author: Wafel & Cyanox
        - Version: 3.0.2
        - Required Exiled Version: 3.0.0
        - Prefix: PFE
        - Priority: Medium
UnlimitedRadioBattery:
        - Author: SoraCént
        - Version: 0.1.0
        - Required Exiled Version: 3.0.0
        - Prefix: unlimited_radio_battery
        - Priority: Medium
Admin Tools:
        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
        - Version: 3.0.3
        - Required Exiled Version: 3.0.0
        - Prefix: AT
        - Priority: Medium
SupplyDrop:
        - Author: Wafel, KadeDev, JesusQC
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: SD
        - Priority: Medium
CustomWarheadColor:
        - Author: SoraCént
        - Version: 0.1.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom_warhead_color
        - Priority: Medium
SmartDisconnect:
        - Author: TemmieGamerGuy
        - Version: 1.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: smart_disconnect
        - Priority: Medium
Common Utilities:
        - Author: Galaxy119
        - Version: 4.2.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: CommonUtilities
        - Priority: Medium
RemoteKeycard:
        - Author: Beryl
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: remotekeycard
        - Priority: Medium

**Additional context**
No.

**Comment by joker-119** [comment]
If you included the entire CU config like is asked for I wouldn't need to ask this..

Do you have the ``scps_immune_to914_effects`` option set to true?

**Comment by joker-119** [comment]
Cannot reproduce, both configs work as expected.
