### ISSUE TITLE
Class Change will enable friendlyfire if changed to an allied class

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/Common-Utils#62]
**Describe the bug**
Example: If you change to facility guard but you were class D, you can FF other facility guards with a gun.

**To Reproduce**
1. Use SCP-914 class change config.

**Expected behavior**
Read description.

**Server logs**
None.

**Copy of current CU config section**
 scp914_class_changes:
    Rough:
    - original: NtfCaptain
      new: NtfSpecialist
      chance: 15
    - original: NtfSpecialist
      new: NtfSergeant
      chance: 15
    - original: NtfSergeant
      new: NtfPrivate
      chance: 15
    - original: NtfPrivate
      new: FacilityGuard
      chance: 15
    - original: FacilityGuard
      new: Scientist
      chance: 15
    - original: ChaosMarauder
      new: ChaosConscript
      chance: 15
    - original: ChaosConscript
      new: ChaosRepressor
      chance: 15
    - original: ChaosRepressor
      new: ChaosRifleman
      chance: 15
    - original: ChaosRifleman
      new: ClassD
      chance: 15
    OneToOne:
    - original: Scp106
      new: Scp93953
      chance: 100
    - original: Scp049
      new: Scp106
      chance: 100
    - original: Scp93989
      new: Scp049
      chance: 100
    - original: Scp93953
      new: Scp93989
      chance: 100
    - original: NtfCaptain
      new: ChaosMarauder
      chance: 15
    - original: NtfSpecialist
      new: ChaosConscript
      chance: 15
    - original: NtfSergeant
      new: ChaosRepressor
      chance: 15
    - original: NtfPrivate
      new: ChaosRifleman
      chance: 15
    - original: ChaosMarauder
      new: NtfCaptain
      chance: 15
    - original: ChaosRepressor
      new: NtfSergeant
      chance: 15
    - original: ChaosConscript
      new: NtfSpecialist
      chance: 15
    - original: ChaosRifleman
      new: NtfPrivate
      chance: 15
    - original: ClassD
      new: Scientist
      chance: 15
    - original: Scientist
      new: ClassD
      chance: 15
    Fine:
    - original: Scp0492
      new: ClassD
      chance: 15
    - original: Scp0492
      new: Scientist
      chance: 15
    VeryFine:
    - original: NtfSpecialist
      new: NtfCaptain
      chance: 15
    - original: NtfSergeant
      new: NtfSpecialist
      chance: 15
    - original: NtfPrivate
      new: NtfSergeant
      chance: 15
    - original: FacilityGuard
      new: NtfPrivate
      chance: 15
    - original: ChaosConscript
      new: ChaosMarauder
      chance: 15
    - original: ChaosRepressor
      new: ChaosConscript
      chance: 15
    - original: ChaosRifleman
      new: ChaosRepressor
      chance: 15
    - original: ClassD
      new: ChaosRifleman
      chance: 15
    - original: Scientist
      new: FacilityGuard
      chance: 15

**EXILED Version ("latest" is not a version):**
Version 83

**Results of `show plugins` command in console:**
Exiled.Events:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_events
        - Priority: Highest
Stalky106:
        - Author: RogerFK
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: ST106
        - Priority: Medium
RespawnTimer:
        - Author: Michal78900
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: respawn_timer
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 4.0.5.0
        - Required Exiled Version: 3.0.0
        - Prefix: discord_integration
        - Priority: Medium
Custom096:
        - Author: Build
        - Version: 1.0.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom096
        - Priority: Medium
Exiled.Updater:
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_updater
        - Priority: Medium
CustomAnnouncements:
        - Author: Build
        - Version: 1.1.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom_announcements
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_credits
        - Priority: Medium
PeanutFckingExplodes:
        - Author: Wafel & Cyanox
        - Version: 3.0.2
        - Required Exiled Version: 3.0.0
        - Prefix: PFE
        - Priority: Medium
UnlimitedRadioBattery:
        - Author: SoraCént
        - Version: 0.1.0
        - Required Exiled Version: 3.0.0
        - Prefix: unlimited_radio_battery
        - Priority: Medium
Admin Tools:
        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
        - Version: 3.0.3
        - Required Exiled Version: 3.0.0
        - Prefix: AT
        - Priority: Medium
SupplyDrop:
        - Author: Wafel, KadeDev, JesusQC
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: SD
        - Priority: Medium
CustomWarheadColor:
        - Author: SoraCént
        - Version: 0.1.0
        - Required Exiled Version: 3.0.0
        - Prefix: custom_warhead_color
        - Priority: Medium
SmartDisconnect:
        - Author: TemmieGamerGuy
        - Version: 1.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: smart_disconnect
        - Priority: Medium
Common Utilities:
        - Author: Galaxy119
        - Version: 4.2.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: CommonUtilities
        - Priority: Medium
RemoteKeycard:
        - Author: Beryl
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: remotekeycard
        - Priority: Medium

**Additional context**
None.

**Comment by joker-119** [comment]
Are you reporting this as a bug that actually occurs, or a feature request?

**Comment by JustJesseGITHUB** [comment]
idk tbh but the two other configs dont work i had them both set to true and a person gains more than 1 effect from 914 at a time so
