### ISSUE TITLE
Need help with SCP class changing

### ISSUE THREAD

**Issue by NoSkillJustJosh2** [Exiled-Team/Common-Utils#63]
**Describe the bug**
SCPs will not change in 914 when I have set the config up to do so/

**To Reproduce**
1. Set an SCP class to 1:1 (I used 11 in config)
2. Set it to any other SCP
3. set chance to 100
4. Try to change classes, fail.

**Expected behavior**
SCP to change.

**Comment by joker-119** [comment]
Please provide everything that you arbitrarily erased from the bug report template

**Comment by joker-119** [comment]
Tested, SCP class changing works fine.
