### ISSUE TITLE
Cannot change an Scp's max health

### ISSUE THREAD

**Issue by NBH0609** [Exiled-Team/Common-Utils#64]
When trying to set an scp's max health beneath its default value, it will not work. This only happens at the beginning of the game, to whoever spawns as an Scp. Apparently this is due to northwood's bad code, but I'm sure the plugin can fix it as well.

**Comment by joker-119** [comment]
Please use the bug report template, it exists for a reason (so I don't have to constantly ask the same questions over and over)
