### ISSUE TITLE
AmmoLimit not working properly  - just add bigger delay to adding ammo

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/Common-Utils#69]
**Describe the bug**
Yeah yeah so you can't make a starter ammo limit because it bugs out

**To Reproduce**
Just set each ammo limit to like 100 and test

**Expected behavior**
Can't set a custom ammo limit

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured
No logs to prove that

**Copy of current CU config section**
CommonUtilities:
# Wether or not debug messages should be shown.
  debug: false
  # The SCP Roles able to use V to talk to humans.
  scp_speech:
  - Scp096
  - Scp106
  - Scp173
  - Scp049
  - Scp0492
  # Whether or not MTF/CI can 'escape' while disarmed to switch teams.
  disarm_switch_teams: false
  # Whether or not disarmed people will be prevented from interacting with doors/elevators.
  restrictive_disarming: false
  # The text displayed at the timed interval specified below.
  timed_broadcast: ''
  # The time each timed broadcast will be displayed.
  timed_broadcast_duration: 0
  # The delay between each timed broadcast. To disable timed broadcasts, set this to 0
  timed_broadcast_delay: 0
  # The message displayed to the player when they first join the server. Setting this to empty will disable these broadcasts.
  join_message: <color=#9e0000><size=30><b>WELCOME TO LABORATORY MAYHEM! MAKE SURE TO READ THE RULES!</b></size></color>
  # The amount of time (in seconds) the join message is displayed.
  join_message_duration: 10
  # The amount of time (in seconds) after the round starts, before the facilities auto-nuke will start.
  autonuke_time: -1
  # Wether or not the nuke should be unable to be disabled during the auto-nuke countdown.
  autonuke_lock: false
  # The list of starting items for roles. ItemName is the item to give them, and Chance is the percent chance of them spawning with it, and Group allows you to restrict the item to only players with certain RA groups (Leave this as 'none' to allow all players to get the item). You can specify the same item multiple times.
  starting_inventories:
    NtfCaptain:
      slot1:
      - item_name: ArmorHeavy
        chance: 100
        group: none
      slot2:
      - item_name: GunE11SR
        chance: 100
        group: none
      slot3:
      - item_name: KeycardNTFCommander
        chance: 100
        group: none
      - item_name: KeycardO5
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: Adrenaline
        chance: 100
        group: none
      slot6:
      - item_name: GrenadeHE
        chance: 100
        group: none
      slot7:
      - item_name: Radio
        chance: 100
        group: none
      slot8:
      - item_name: Flashlight
        chance: 100
        group: none
      ammo:
      - type: Ammo9x19
        amount: 50
        group: none
      - type: Ammo556x45
        amount: 50
        group: none
      - type: Ammo762x39
        amount: 50
        group: none
      - type: Ammo44cal
        amount: 50
        group: none
      - type: Ammo12gauge
        amount: 50
        group: none
    NtfSpecialist:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunE11SR
        chance: 100
        group: none
      slot3:
      - item_name: KeycardNTFLieutenant
        chance: 100
        group: none
      - item_name: KeycardNTFCommander
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: GrenadeHE
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7:
      - item_name: Flashlight
        chance: 100
        group: none
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 50
        group: none
      - type: Ammo556x45
        amount: 50
        group: none
      - type: Ammo762x39
        amount: 50
        group: none
      - type: Ammo44cal
        amount: 50
        group: none
      - type: Ammo12gauge
        amount: 50
        group: none
    NtfSergeant:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunE11SR
        chance: 100
        group: none
      slot3:
      - item_name: KeycardNTFLieutenant
        chance: 100
        group: none
      - item_name: KeycardNTFCommander
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: GrenadeHE
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7:
      - item_name: Flashlight
        chance: 100
        group: none
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 50
        group: none
      - type: Ammo556x45
        amount: 50
        group: none
      - type: Ammo762x39
        amount: 50
        group: none
      - type: Ammo44cal
        amount: 50
        group: none
      - type: Ammo12gauge
        amount: 50
        group: none
    NtfPrivate:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunCrossvec
        chance: 100
        group: none
      slot3:
      - item_name: KeycardNTFOfficer
        chance: 100
        group: none
      - item_name: KeycardNTFLieutenant
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: GrenadeFlash
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7:
      - item_name: Flashlight
        chance: 100
        group: none
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 50
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 25
        group: 
      - type: Ammo44cal
        amount: 25
        group: 
      - type: Ammo12gauge
        amount: 25
        group: 
    ChaosMarauder:
      slot1:
      - item_name: ArmorHeavy
        chance: 100
        group: none
      slot2:
      - item_name: GunLogicer
        chance: 100
        group: none
      slot3:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      - item_name: KeycardO5
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: Adrenaline
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7:
      - item_name: Flashlight
        chance: 100
        group: none
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 25
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 50
        group: 
      - type: Ammo44cal
        amount: 25
        group: 
      - type: Ammo12gauge
        amount: 25
        group: 
    ChaosConscript:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunAK
        chance: 100
        group: none
      slot3:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: Painkillers
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7:
      - item_name: Flashlight
        chance: 100
        group: none
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 25
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 50
        group: 
      - type: Ammo44cal
        amount: 25
        group: 
      - type: Ammo12gauge
        amount: 25
        group: 
    ChaosRepressor:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunShotgun
        chance: 100
        group: none
      slot3:
      - item_name: GunRevolver
        chance: 100
        group: none
      slot4:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot5:
      - item_name: Medkit
        chance: 100
        group: none
      slot6:
      - item_name: Painkillers
        chance: 100
        group: none
      slot7:
      - item_name: Radio
        chance: 100
        group: none
      slot8:
      - item_name: Flashlight
        chance: 100
        group: none
      ammo:
      - type: Ammo9x19
        amount: 25
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 25
        group: 
      - type: Ammo44cal
        amount: 50
        group: 
      - type: Ammo12gauge
        amount: 50
        group: 
    ChaosRifleman:
      slot1:
      - item_name: ArmorCombat
        chance: 100
        group: none
      slot2:
      - item_name: GunAK
        chance: 100
        group: none
      slot3:
      - item_name: KeycardChaosInsurgency
        chance: 100
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: Painkillers
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7: []
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 25
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 25
        group: 
      - type: Ammo44cal
        amount: 25
        group: 
      - type: Ammo12gauge
        amount: 25
        group: 
    FacilityGuard:
      slot1:
      - item_name: ArmorLight
        chance: 100
        group: none
      slot2:
      - item_name: GunFSP9
        chance: 100
        group: none
      slot3:
      - item_name: KeycardGuard
        chance: 100
        group: none
      - item_name: KeycardNTFOfficer
        chance: 15
        group: none
      slot4:
      - item_name: Medkit
        chance: 100
        group: none
      slot5:
      - item_name: GrenadeFlash
        chance: 100
        group: none
      slot6:
      - item_name: Radio
        chance: 100
        group: none
      slot7: []
      slot8: []
      ammo:
      - type: Ammo9x19
        amount: 25
        group: 
      - type: Ammo556x45
        amount: 25
        group: 
      - type: Ammo762x39
        amount: 25
        group: 
      - type: Ammo44cal
        amount: 25
        group: 
      - type: Ammo12gauge
        amount: 25
        group: 
    ClassD:
      slot1:
      - item_name: KeycardScientist
        chance: 15
        group: none
      slot2:
      - item_name: Flashlight
        chance: 100
        group: none
      slot3:
      - item_name: Coin
        chance: 100
        group: none
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo: []
    Scientist:
      slot1:
      - item_name: KeycardScientist
        chance: 100
        group: none
      - item_name: KeycardZoneManager
        chance: 15
        group: none
      slot2:
      - item_name: Medkit
        chance: 100
        group: none
      slot3:
      - item_name: Radio
        chance: 100
        group: none
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo: []
  # The list of custom 914 recipies. Original is the item being upgraded, New is the item to upgrade to, and Chance is the percent chance of the upgrade happening. You can specify multiple upgrade choices for the same item.
  scp914_item_changes:
    Fine:
    - original: GunCOM15
      new: GunCOM18
      chance: 100
    - original: GunCOM18
      new: GunFSP9
      chance: 100
    - original: GunFSP9
      new: GunCrossvec
      chance: 100
    - original: GunCrossvec
      new: GunE11SR
      chance: 100
    - original: GunE11SR
      new: GunAK
      chance: 100
    - original: GunAK
      new: GunRevolver
      chance: 100
    - original: GunRevolver
      new: GunShotgun
      chance: 100
    - original: GunShotgun
      new: GunLogicer
      chance: 100
    - original: GunLogicer
      new: GunCOM15
      chance: 100
    - original: Ammo9x19
      new: Ammo556x45
      chance: 100
    - original: Ammo556x45
      new: Ammo762x39
      chance: 100
    - original: Ammo762x39
      new: Ammo44cal
      chance: 100
    - original: Ammo44cal
      new: Ammo12gauge
      chance: 100
    - original: Ammo12gauge
      new: Ammo9x19
      chance: 100
    - original: Coin
      new: KeycardZoneManager
      chance: 50
    - original: Flashlight
      new: GrenadeFlash
      chance: 25
    - original: Coin
      new: KeycardO5
      chance: 15
    - original: Coin
      new: KeycardFacilityManager
      chance: 15
    - original: Coin
      new: SCP268
      chance: 15
    - original: Coin
      new: SCP018
      chance: 15
    - original: Coin
      new: SCP207
      chance: 15
    - original: Coin
      new: SCP500
      chance: 15
    VeryFine:
    - original: GrenadeFlash
      new: SCP207
      chance: 100
    - original: Flashlight
      new: GrenadeFlash
      chance: 75
    - original: GunCOM15
      new: GunFSP9
      chance: 50
    - original: GunCOM18
      new: GunE11SR
      chance: 50
    - original: GunFSP9
      new: GunE11SR
      chance: 50
    - original: GunE11SR
      new: GunRevolver
      chance: 50
    - original: GunAK
      new: GunShotgun
      chance: 50
    - original: GunShotgun
      new: GunCOM15
      chance: 50
    - original: GunRevolver
      new: GunLogicer
      chance: 50
    - original: GunLogicer
      new: GunCOM18
      chance: 50
    - original: GunCOM15
      new: None
      chance: 50
    - original: GunCOM18
      new: None
      chance: 50
    - original: GunFSP9
      new: None
      chance: 50
    - original: GunE11SR
      new: None
      chance: 50
    - original: GunAK
      new: None
      chance: 50
    - original: GunShotgun
      new: None
      chance: 50
    - original: GunRevolver
      new: None
      chance: 50
    - original: GunLogicer
      new: None
      chance: 50
    - original: Ammo9x19
      new: Ammo762x39
      chance: 50
    - original: Ammo556x45
      new: Ammo44cal
      chance: 50
    - original: Ammo762x39
      new: Ammo12gauge
      chance: 50
    - original: Ammo44cal
      new: Ammo9x19
      chance: 50
    - original: Ammo12gauge
      new: Ammo556x45
      chance: 50
    - original: Ammo9x19
      new: None
      chance: 50
    - original: Ammo556x45
      new: None
      chance: 50
    - original: Ammo762x39
      new: None
      chance: 50
    - original: Ammo44cal
      new: None
      chance: 50
    - original: Ammo12gauge
      new: None
      chance: 50
    - original: GrenadeHE
      new: SCP018
      chance: 50
    - original: GrenadeHE
      new: None
      chance: 50
    - original: Painkillers
      new: SCP500
      chance: 50
    - original: Painkillers
      new: None
      chance: 50
    - original: Flashlight
      new: None
      chance: 50
    - original: Radio
      new: GunCOM18
      chance: 25
    - original: Coin
      new: Ammo44cal
      chance: 25
    - original: Coin
      new: Ammo9x19
      chance: 25
    - original: Coin
      new: Ammo556x45
      chance: 25
    - original: Coin
      new: Ammo762x39
      chance: 25
    - original: Coin
      new: Ammo44cal
      chance: 25
    - original: Coin
      new: Ammo12gauge
      chance: 25
    - original: Coin
      new: GunLogicer
      chance: 15
    - original: Coin
      new: GunE11SR
      chance: 15
    - original: KeycardO5
      new: GunCrossvec
      chance: 15
    - original: KeycardO5
      new: GunShotgun
      chance: 15
  # The list of custom 914 recipies for roles. Original is the role to be changed, New is the new role to assign, Chance is the % chance of the upgrade occuring.
  scp914_class_changes:
    Rough:
    - original: NtfCaptain
      new: NtfSpecialist
      chance: 15
    - original: NtfSpecialist
      new: NtfSergeant
      chance: 15
    - original: NtfSergeant
      new: NtfPrivate
      chance: 15
    - original: NtfPrivate
      new: FacilityGuard
      chance: 15
    - original: FacilityGuard
      new: Scientist
      chance: 15
    - original: ChaosMarauder
      new: ChaosConscript
      chance: 15
    - original: ChaosConscript
      new: ChaosRepressor
      chance: 15
    - original: ChaosRepressor
      new: ChaosRifleman
      chance: 15
    - original: ChaosRifleman
      new: ClassD
      chance: 15
    OneToOne:
    - original: Scp106
      new: Scp93953
      chance: 100
    - original: Scp049
      new: Scp106
      chance: 100
    - original: Scp93989
      new: Scp049
      chance: 100
    - original: Scp93953
      new: Scp93989
      chance: 100
    - original: NtfCaptain
      new: ChaosMarauder
      chance: 15
    - original: NtfSpecialist
      new: ChaosConscript
      chance: 15
    - original: NtfSergeant
      new: ChaosRepressor
      chance: 15
    - original: NtfPrivate
      new: ChaosRifleman
      chance: 15
    - original: Scientist
      new: ClassD
      chance: 15
    - original: ChaosMarauder
      new: NtfCaptain
      chance: 15
    - original: ChaosRepressor
      new: NtfSergeant
      chance: 15
    - original: ChaosConscript
      new: NtfSpecialist
      chance: 15
    - original: ChaosRifleman
      new: NtfPrivate
      chance: 15
    - original: ClassD
      new: Scientist
      chance: 15
    Fine:
    - original: Scp0492
      new: Scientist
      chance: 15
    - original: Scp0492
      new: ClassD
      chance: 15
    VeryFine:
    - original: NtfSpecialist
      new: NtfCaptain
      chance: 15
    - original: NtfSergeant
      new: NtfSpecialist
      chance: 15
    - original: NtfPrivate
      new: NtfSergeant
      chance: 15
    - original: FacilityGuard
      new: NtfPrivate
      chance: 15
    - original: Scientist
      new: FacilityGuard
      chance: 15
    - original: ChaosConscript
      new: ChaosMarauder
      chance: 15
    - original: ChaosRepressor
      new: ChaosConscript
      chance: 15
    - original: ChaosRifleman
      new: ChaosRepressor
      chance: 15
    - original: ClassD
      new: ChaosRifleman
      chance: 15
  scp914_teleport_chances:
    Coarse:
    - room: LczCrossing
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
    - room: LczTCross
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
    - room: LczChkpA
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 0
    - room: LczChkpB
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 0
    - room: Lcz914
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
    - room: HczEzCheckpoint
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 0
    - room: HczTCross
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
    - room: HczServers
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
    - room: EzGateA
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 0
    - room: EzGateB
      offset:
        x: 0
        y: 0
        z: 0
      chance: 15
      damage: 0
    - room: EzStraight
      offset:
        x: 0
        y: 0
        z: 0
      chance: 25
      damage: 0
  # A dictionary of random effects to apply to players when going through 914 on certain settings.
  scp914_effect_chances:
    Fine:
    - effect: Invisible
      chance: 5
      duration: 15
    - effect: Invigorated
      chance: 5
      duration: 15
    - effect: Visuals939
      chance: 5
      duration: 15
    - effect: Scp207
      chance: 5
      duration: 15
    - effect: Poisoned
      chance: 5
      duration: 15
    - effect: Bleeding
      chance: 5
      duration: 15
    - effect: Hemorrhage
      chance: 5
      duration: 15
    VeryFine:
    - effect: Invisible
      chance: 5
      duration: 25
    - effect: Invigorated
      chance: 5
      duration: 25
    - effect: Visuals939
      chance: 5
      duration: 25
    - effect: Scp207
      chance: 5
      duration: 25
    - effect: Poisoned
      chance: 5
      duration: 25
    - effect: Bleeding
      chance: 5
      duration: 25
    - effect: Hemorrhage
      chance: 5
      duration: 25
  # Determines if 914 effects are exclusive, meaning only one can be applied each time a player is processed by 914.
  scp914_effects_exclusivity: true
  # Whether or not SCPs are immune to effects gained from 914.
  scps_immune_to914_effects: true
  # The frequency (in seconds) between ragdoll cleanups. Set to 0 to disable.
  ragdoll_cleanup_delay: 0
  # If ragdoll cleanup should only happen in the Pocket Dimension or not.
  ragdoll_cleanup_only_pocket: false
  # The frequency (in seconds) between item cleanups. Set to 0 to disable.
  item_cleanup_delay: 0
  # If item cleanup should only happen in the Pocket Dimension or not.
  item_cleanup_only_pocket: false
  # A list of all roles and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  role_damage_multipliers:
    Scp93989: 1.10000002
    Scp93953: 1.10000002
  # A list of all Weapons and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  weapon_damage_multipliers: {}
  # A list of roles and how much health they should be given when they kill someone.
  health_on_kill:
    Scp173: 50
    Scp049: 50
    Scp93989: 25
    Scp93953: 25
  # A list of roles and what their default starting health should be.
  health_values:
    Scp096: 2000
    Scp106: 1000
    Scp173: 3000
    Scp049: 3000
    Scp93989: 2400
    Scp93953: 2400
    Scp0492: 750
    Tutorial: 1000000
    NtfCaptain: 200
    NtfSpecialist: 150
    NtfSergeant: 150
    NtfPrivate: 125
    FacilityGuard: 110
    Scientist: 110
    ChaosMarauder: 200
    ChaosRepressor: 150
    ChaosConscript: 150
    ChaosRifleman: 125
    ClassD: 110
  # If the plugin is enabled or not.
  is_enabled: true

**EXILED Version ("latest" is not a version):**
3.0.0-beta.3

**Results of `show plugins` command in console:**

**Additional context**

**Comment by joker-119** [comment]
I will investigate this, but in the future, use code tags or a pastebin for the config section.

Also you gave an invalid exiled version, there is no 3.0.0-beta.3, so I'm assuming you mean 3.0.3-beta

**Comment by JustJesseGITHUB** [comment]
this is what i mean https://gyazo.com/284f65c02046968c93a9acc4662920a1 so i have all other ammo values except 9x19mm set to 50 and 9x19mm is set to 100 but only gives 70 on spawn

**Comment by joker-119** [comment]
Apparently this is still happening

**Comment by Hamster12012** [comment]
Any ETA of fixing this issue ? Not recent update on this issue since 10 days @joker-119
