### ISSUE TITLE
[BUG] Error on 079 recontainment

### ISSUE THREAD

**Issue by EsserGaming** [Exiled-Team/Common-Utils#73]
When 079 dies due to being the last SCP or due to all generators being activated. The error doesn't seem to cause any real issues other than an error in the console.

**The error:**

> [2021-10-11 17:26:02] [ERROR] [Exiled.Events] Method "OnPlayerDied" of the class "Common_Utilities.EventHandlers.PlayerHandlers" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler1[[Exiled.Events.EventArgs.DiedEventArgs, Exiled.Events, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null]]"
> [2021-10-11 17:26:02] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object
>   at Common_Utilities.EventHandlers.PlayerHandlers.OnPlayerDied (Exiled.Events.EventArgs.DiedEventArgs ev) [0x00017] in <5e3b77f61cee4ba6aff9bbcb73923130>:0 
>   at Exiled.Events.Extensions.Event.InvokeSafely[T] (Exiled.Events.Events+CustomEventHandler1[TEventArgs] ev, T arg) [0x00024] in <fc558e63e9354fa28c2154a8806da322>:0

**EXILED Version:**
3.0.5

**Results of `show plugins` command in console:**

> [2021-10-11 17:31:42] Total number of plugins: 19
> Enabled plugins: 18
> Disabled plugins: 1
> 
> Exiled.Events:
>         - Author: Exiled Team
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: exiled_events
>         - Priority: Highest
> CedMod:
>         - Author: ced777ric#0001
>         - Version: 3.0.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: cm
>         - Priority: Highest
> EasyEvents:
>         - Author: Johnodon
>         - Version: 1.0.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: easy_events
>         - Priority: Medium
> DiscordIntegration:
>         - Author: Exiled Team
>         - Version: 4.0.6.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: discord_integration
>         - Priority: Medium
> Stalky106:
>         - Author: RogerFK
>         - Version: 3.0.0.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: ST106
>         - Priority: Medium
> RespawnTimer:
>         - Author: Michal78900
>         - Version: 3.0.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: respawn_timer
>         - Priority: Medium
> Exiled.CustomItems:
>         - Author: Exiled Team
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: exiled_custom_items
>         - Priority: Medium
> Exiled.CreditTags:
>         - Author: Babyboucher20 & iRebbok & Exiled Team
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: exiled_credits
>         - Priority: Medium
> CoinTweaks:
>         - Author: GabiRP
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: coin_tweaks
>         - Priority: Medium
> Exiled.CustomRoles:
>         - Author: Exiled Team
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: exiled_custom_roles
>         - Priority: Medium
> Lucky Pills:
>         - Author: NutInc
>         - Version: 3.1.4
>         - Required Exiled Version: 3.0.0.0
>         - Prefix: lucky_pills
>         - Priority: Medium
> RainbowLobby:
>         - Author: Jesus-QC
>         - Version: 1.0.1.1
>         - Required Exiled Version: 3.0.0
>         - Prefix: RainbowLobby
>         - Priority: Medium
> CedMod-WebAPI:
>         - Author: ced777ric#0001
>         - Version: 3.0.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: cm_WAPI
>         - Priority: Medium
> OnlySCP:
>         - Author: Build
>         - Version: 1.0.1.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: only_s_c_p
>         - Priority: Medium
> AutoFFToggle:
>         - Author: Kognity
>         - Version: 1.7.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: auto_f_f_toggle
>         - Priority: Medium
> Exiled.Permissions:
>         - Author: Exiled Team
>         - Version: 3.0.5.0
>         - Required Exiled Version: 3.0.5.0
>         - Prefix: exiled_permissions
>         - Priority: Medium
> Admin Tools:
>         - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
>         - Version: 3.0.4.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: AT
>         - Priority: Medium
> LogArchiver:
>         - Disabled
>         - Author: Galaxy119
>         - Version: 1.0.0
>         - Required Exiled Version: 2.1.18
>         - Prefix: LogArchiver
>         - Priority: Medium
> Common Utilities:
>         - Author: Galaxy119
>         - Version: 4.2.4.0
>         - Required Exiled Version: 3.0.0
>         - Prefix: CommonUtilities
>         - Priority: Medium

If there is anything else you need please tell me.

**Comment by joker-119** [comment]
I need the config section for CU, hence why it's in the bug report template.

**Comment by EsserGaming** [comment]
> I need the config section for CU, hence why it's in the bug report template.

What section?

**Comment by joker-119** [comment]
This was an issue with EXILED calling the OnDying event for 079 twice, and was resolved in 3.3.1
