### ISSUE TITLE
Change AutonukeTime default to 86400 instead of 600 if configs break

### ISSUE THREAD

**Issue by PatPeter** [Exiled-Team/Common-Utils#79]
**Describe the bug**
If the configs break or the server owner typos yaml, then ALL CommonUtilities configs will resort to default.

**To Reproduce**
1. Add invalid YAML to the EXILED configs for CommonUtilites or do a bad refresh in EXILED.
2. Autonuke is set to 10 minutes.

**Expected behavior**
Autonuke should not resort to a default of 10 minutes if the server owner screws something up or EXILED does a bad refresh.

**Comment by joker-119** [comment]
I think having the default autonuke timer be 60 days instead of 10 minutes is a bit of an over-correction. I will instead set the default to 25mins in future versions.

**Comment by PatPeter** [comment]
Wait the default is seconds, not minutes right? 86400 seconds is 1 day.

**Comment by joker-119** [comment]
Sorry yes, seconds not minutes, but still, I feel like 1 full day is still an overcorrection, it might as well default to disabled at that point lmao

**Comment by joker-119** [comment]
Adjusted in 359ef664f834cce227eb1645e0091ff5bd0921c7
