### ISSUE TITLE
Nametag compatibility issue (Health Tag)

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/Common-Utils#80]
**Describe the bug**
If you turn on the config to show a players health when hovering over them, a Serpents Hand or UIU squad member's tag does not show.

**To Reproduce**
Make sure you have Serpents Hand or UIU Squad installed
Make yourself one of them
Have someone hover over you with the show health config on

**Expected behavior**
Should show the players health and their tag

**Server logs**
None

**Copy of current CU config section**
https://pastebin.com/4zXZFZY2

**EXILED Version ("latest" is not a version):**
3.7.2

**Results of `show plugins` command in console:**
Total: 20
Active: 20
Disabled: 0

**Additional context**

**Comment by joker-119** [comment]
This isn't exactly a bug, it's not within the design of this plugin to ensure compatibility with every other possible plugin being used, as that would likely be impossible to do, but I believe I can rework the health display system to accommodate other plugins using the custom info field.
