### ISSUE TITLE
error being spammed in console

### ISSUE THREAD

**Issue by growled** [Exiled-Team/Common-Utils#81]
**Describe the bug**
Error being spammed in console

**To Reproduce**
Play on a server with the latest version 5.0.1

**Expected behavior**
The error not to appear.

**Server logs**
![image](https://user-images.githubusercontent.com/77838632/144304290-1fcb7a83-aae0-4eb2-b2c3-988bc16af116.png)

**Copy of current CU config section**
CommonUtilities:
# Wether or not debug messages should be shown.
  debug: false
  # The SCP Roles able to use V to talk to humans.
  scp_speech:
  - Scp049
  # Whether or not MTF/CI can 'escape' while disarmed to switch teams.
  disarm_switch_teams: false
  # Whether or not disarmed people will be prevented from interacting with doors/elevators.
  restrictive_disarming: true
  # The text displayed at the timed interval specified below.
  timed_broadcast: <b><color=purple>Welcome to Noah's Nation! We have <color=#7289DA>Discord (discord.gg/noahsnation)</color> and <color=#f96854>Patreon (patreon.com/noahsnation)</color> for server perks!</color></b>
  # The time each timed broadcast will be displayed.
  timed_broadcast_duration: 30
  # The delay between each timed broadcast. To disable timed broadcasts, set this to 0
  timed_broadcast_delay: 300
  # The message displayed to the player when they first join the server. Setting this to empty will disable these broadcasts.
  join_message: <color=purple>Welcome back %player%! You can report rule breakers by pressing N and choosing the player to report. Thanks for making our community a better place!</color>
  # The amount of time (in seconds) the join message is displayed.
  join_message_duration: 5
  # The amount of time (in seconds) after the round starts, before the facilities auto-nuke will start.
  autonuke_time: 1500
  # Wether or not the nuke should be unable to be disabled during the auto-nuke countdown.
  autonuke_lock: true
  # Whether or not to show player's health under their name when you look at them.
  player_health_info: false
  # The list of starting items for roles. ItemName is the item to give them, and Chance is the percent chance of them spawning with it, and Group allows you to restrict the item to only players with certain RA groups (Leave this as 'none' to allow all players to get the item). You can specify the same item multiple times.
  starting_inventories:
    ClassD:
      slot1:
      - item_name: Flashlight
        chance: 100
        group: none
      slot2:
      - item_name: Coin
        chance: 100
        group: none
      slot3: []
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo: []
  # The list of custom 914 recipies. Original is the item being upgraded, New is the item to upgrade to, and Chance is the percent chance of the upgrade happening. You can specify multiple upgrade choices for the same item.
  scp914_item_changes:
    Rough: []
  # The list of custom 914 recipies for roles. Original is the role to be changed, New is the new role to assign, Chance is the % chance of the upgrade occuring.
  scp914_class_changes:
    Rough:
    - original: Scp173
      new: Spectator
      chance: 100
    - original: ClassD
      new: Spectator
      chance: 100
    - original: Scp106
      new: Spectator
      chance: 100
    - original: NtfSpecialist
      new: Spectator
      chance: 100
    - original: Scp049
      new: Spectator
      chance: 100
    - original: Scientist
      new: Spectator
      chance: 100
    - original: ChaosConscript
      new: Spectator
      chance: 100
    - original: Scp096
      new: Spectator
      chance: 100
    - original: NtfSergeant
      new: Spectator
      chance: 100
    - original: NtfCaptain
      new: Spectator
      chance: 100
    - original: NtfPrivate
      new: Spectator
      chance: 100
    - original: Tutorial
      new: Spectator
      chance: 100
    - original: FacilityGuard
      new: Spectator
      chance: 100
    - original: Scp93953
      new: Spectator
      chance: 100
    - original: Scp93989
      new: Spectator
      chance: 100
    - original: ChaosRifleman
      new: Spectator
      chance: 100
    - original: ChaosRepressor
      new: Spectator
      chance: 100
    - original: ChaosMarauder
      new: Spectator
      chance: 100
  scp914_teleport_chances:
    Rough: []
  # A dictionary of random effects to apply to players when going through 914 on certain settings.
  scp914_effect_chances:
    Rough: []
  # Determines if 914 effects are exclusive, meaning only one can be applied each time a player is processed by 914.
  scp914_effects_exclusivity: false
  # Whether or not SCPs are immune to effects gained from 914.
  scps_immune_to914_effects: false
  # The frequency (in seconds) between ragdoll cleanups. Set to 0 to disable.
  ragdoll_cleanup_delay: 0
  # If ragdoll cleanup should only happen in the Pocket Dimension or not.
  ragdoll_cleanup_only_pocket: false
  # The frequency (in seconds) between item cleanups. Set to 0 to disable.
  item_cleanup_delay: 0
  # If item cleanup should only happen in the Pocket Dimension or not.
  item_cleanup_only_pocket: false
  # A list of all roles and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  role_damage_multipliers:
    Scp173: 1
  # A list of all Weapons and their damage modifiers. The number here is a multiplier, not a raw damage amount. Thus, setting it to 1 = normal damage, 1.5 = 50% more damage, and 0.5 = 50% less damage.
  weapon_damage_multipliers:
    GunE11SR: 1
  # A list of roles and how much health they should be given when they kill someone.
  health_on_kill:
    Scp173: 50
    Scp096: 25
  # A list of roles and what their default starting health should be.
  health_values:
    NtfCaptain: 120
    ChaosRifleman: 100
    Scp173: 3000
    ClassD: 100
    FacilityGuard: 100
    Scientist: 100
  # If the plugin is enabled or not.
  is_enabled: true

**EXILED Version ("latest" is not a version):**
4.0.0

**Results of `show plugins` command in console:**
[2021-12-01 19:55:54.562 +00:00] Total number of plugins: 25
                                 Enabled plugins: 23
                                 Disabled plugins: 2

                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 ReportPing:
                                        - Author: Jepp Developments
                                        - Version: 1.1.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: report_ping
                                        - Priority: High
                                 Ban Logger:
                                        - Author: Jesus-QC
                                        - Version: 1.0.7
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: BanLogger
                                        - Priority: Medium
                                 InfiniteAmmo:
                                        - Author: InfiniteAmmo
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: infinite_ammo
                                        - Priority: Medium
                                 Ultimate AFK:
                                        - Author: Thomasjosif
                                        - Version: 3.1.6
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: uAFK
                                        - Priority: Medium
                                 ScpSwap:
                                        - Author: Build
                                        - Version: 1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: scpswap
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Private Broadcast:
                                        - Author: An4r3w & Sans
                                        - Version: 1.0.3
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: Private Broadcast
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Author: Exiled Team
                                        - Version: 5.0.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 BulletHoleManager:
                                        - Author:
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: bullet_hole_manager
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Disabled
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 3.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Medium
                                 AutoEvents:
                                        - Disabled
                                        - Author: Raul125
                                        - Version: 1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: AutoEvents
                                        - Priority: Medium
                                 PlayerList:
                                        - Author: SrLicht
                                        - Version: 1.0.6
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: player_list
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Stalky106:
                                        - Author: RogerFK
                                        - Version: 3.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: ST106
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 4.0.0.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 AutoFFToggle:
                                        - Author: Kognity
                                        - Version: 1.7.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: auto_f_f_toggle
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Galaxy119
                                        - Version: 5.0.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 SerpentsHand:
                                        - Author: Cyanox, maintained by Michal78900
                                        - Version: 3.1.0
                                        - Required Exiled Version: 3.0.5
                                        - Prefix: serpents_hand
                                        - Priority: Medium
                                 BetterSinkholes:
                                        - Author: Thomasjosif, origially written by Blackruby
                                        - Version: 4.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: BSH
                                        - Priority: Medium
                                 Scp096Info:
                                        - Author: VersLugia
                                        - Version: 1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: scp096_info
                                        - Priority: Low
                                 SCPStats:
                                        - Author: PintTheDragon
                                        - Version: 1.5.0
                                        - Required Exiled Version: 4.0.0
                                        - Prefix: scp_stats
                                        - Priority: Lowest

**Additional context**
n/a

**Comment by joker-119** [comment]
Please provide your configs either in code tags or in a pastebin, not a copy/paste that becomes unreadable

**Comment by joker-119** [comment]
I cannot replicate this with default configs, was probably another failure of the NW player auth process or an invalid config value somewhere.

**Comment by growled** [comment]
https://pastebin.com/wmNW0dFt

here's my configs. It's weird because this error is literally being spammed every round, so often that I can't even read the console. It's not just a one time thing.

**Comment by growled** [comment]
Some people are reporting not receiving a flashlight when spawning as ClassD with my config. Still getting this error. It might be something to do with that? Could you retry it with the configs provided above?

**Comment by joker-119** [comment]
Try with version 5.0.4 and reopen this issue if it's still happening.
