### ISSUE TITLE
914 not functioning after 11.1

### ISSUE THREAD

**Issue by SCPSLPLUGINS4ME** [Exiled-Team/Common-Utils#83]
Can't do anything to fix it. Didn't even breath on the settings, and the yamldotnet config is fine. Not like it ruins utils itself, but just something that annoys me. Would be pleased if you could fix this.

**Comment by joker-119** [comment]
When filing a bug report, please use the bug report template.

**Comment by SCPSLPLUGINS4ME** [comment]
Sorry!
