### ISSUE TITLE
Is this supposed to happen?

### ISSUE THREAD

**Issue by Oyplap** [Exiled-Team/Common-Utils#87]
**Describe the bug**
When using the starting_inventories config, I want to add one extra item to the default config on slot7. But the whole inventory gets removed.

**To Reproduce**
1. Go to 'starting_inventories'
2. Add an item on slot7 for a chaos class.
3. inventory gets wiped and no item on slot7

**Expected behavior**
I'm not sure if this is intended. I was hoping that I could add items on (for example) slot7 or 8 without removing the default items from a class.

**Server logs**
Needed for this issue?

**Copy of current CU config section**
  starting_inventories:
    ChaosConscript:
      slot1: []
      slot2: []
      slot3: []
      slot4: []
      slot5: []
      slot6: []
      slot7:
      - item_name: Coin
        chance: 100
        group: Patreon3
      - item_name: Coin
        chance: 100
        group: Patreon4
      slot8: []
      ammo: []

**EXILED Version ("latest" is not a version):**
4.2.5

**Results of `show plugins` command in console:**
                                 Enabled plugins: 16
                                 Disabled plugins: 2
                                 
                                 CedMod:
                                        - Author: ced777ric#8321
                                        - Version: 3.1.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: cm
                                        - Priority: Highest
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 4.2.5.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 4.2.5.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 BetterSinkholes2:
                                        - Disabled
                                        - Author: 
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: better_sinkholes2
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 4.2.5.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 4.2.5.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 ScpSwap:
                                        - Author: Originally written by Cyanox, modifications by KoukoCocoa & Thomasjosif, Maintined by EsserGaming
                                        - Version: 1.0.3
                                        - Required Exiled Version: 4.2.3
                                        - Prefix: scp_swap
                                        - Priority: Medium
                                 RaimbowWaitingScreen:
                                        - Author: JesusQC
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: RaimbowWaitingScreen
                                        - Priority: Medium
                                 CustomLoadouts:
                                        - Author: Build
                                        - Version: 2.2.1.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: customloadouts
                                        - Priority: Medium
                                 BlockingCoin:
                                        - Author: Beryl
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: blocking_coin
                                        - Priority: Medium
                                 RemoteKeycard:
                                        - Author: Beryl
                                        - Version: 3.1.0
                                        - Required Exiled Version: 4.1.0
                                        - Prefix: remotekeycard
                                        - Priority: Medium
                                 Ultimate AFK:
                                        - Author: Thomasjosif
                                        - Version: 3.1.6
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: uAFK
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 4.2.5.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 CustomBadges:
                                        - Author: xRoier
                                        - Version: 1.0.0
                                        - Required Exiled Version: 2.3.3
                                        - Prefix: custombadges
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Galaxy119
                                        - Version: 5.1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 4.0.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Disabled
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 4.2.5.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Author: Exiled Team
                                        - Version: 5.0.2.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium

**Additional context**
no

**Comment by Oyplap** [comment]
> That should be fine, what's the error in your console say?

Haven't found any errors, Also with debug enabled no errors. I was just wondering if you perhaps can make it function differently than removing the entire inventory. I need a replacement for the customloadouts plugin BuildBoy made: https://github.com/BuildBoy12/CustomLoadouts/

**Comment by joker-119** [comment]
Set up the config, then make a copy of the config file, then start the server, and send me both the config file copy and the entire LA log file.

And no, that's not possible, it's likely a formatting error (you're using tabs instead of spaces, or not enough/too many spaces, etc). If a config value fails to validate it gets reset because that's how validation works, but there's also an error involved that you're somehow not seeing.

**Comment by Oyplap** [comment]
[7780-config.txt](https://github.com/Exiled-Team/Common-Utils/files/8422181/7780-config.txt)
[LocalAdmin Log 2022-04-06 00.14.59.txt](https://github.com/Exiled-Team/Common-Utils/files/8422182/LocalAdmin.Log.2022-04-06.00.14.59.txt)

the 7780-config.txt = .yml but I had to upload it as txt because github wouldn't allow yml files

**Comment by joker-119** [comment]
I don't even see a config for chaos conscript in the file you gave.

`  starting_inventories:
    NtfCaptain:
      slot1: []
      slot2: []
      slot3: []
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8:
      - item_name: Flashlight
        chance: 100
        group: owner
      ammo: []`

that's all there is.

I tried replicating your bug myself and cannot, the below config does the same thing yours does and works fine, so it's likely a spacing issue or you are breaking something else in the config.

`  starting_inventories:
    ClassD:
      slot1:
      - item_name: KeycardJanitor
        chance: 10
        group: none
      - item_name: Coin
        chance: 100
        group: none
      slot2:
      - item_name: Flashlight
        chance: 100
        group: none
      slot3:
      - item_name: Coin
        chance: 100
        group: patreon1
      - item_name: Coin
        chance: 100
        group: patreon2
      slot4: []
      slot5: []
      slot6: []
      slot7: []
      slot8: []
      ammo:
      - type: Ammo556x45
        amount: 200
        group: none`

**Comment by Oyplap** [comment]
It’s true, I didn’t include a lot of my configuration. But if you leave slot1 empty, the whole inventory gets removed and the items won’t show up.

**Comment by joker-119** [comment]
It's not erasing the config for me, but I can confirm it stops parsing slot3 (but not slot2) when I set slot1 to `[]`, which is a bug.
For now I would work around it by simply fill out the slots in order, leaving all of the empty slots at the end, not at the start or in the middle of the list of slots.

**Comment by Oyplap** [comment]
Thanks! Oh and the config does not get erased for me. Miscommunication at my end.

**Comment by Oyplap** [comment]
Hi, I have tried the new update but this bug is still arround.
