### ISSUE TITLE
Friendly Fire Turns On

### ISSUE THREAD

**Issue by Heisenberg3666** [Exiled-Team/Common-Utils#88]
Since the new Exiled update, CommonUtilities has been a little buggy. The bug that has occured is related to the "friendly_fire_on_round_end" option. When FFRE is enabled, FF is randomly turned on during the ongoing round. You can disable FF via the "Server Configs" option in the RA console, however this is turned back on after some time. I am certain that it is because of CommonUtilities because when "friendly_fire_on_round_end" is disabled, FF does not automatically turn back on.

**To Reproduce**
1. Go to Exiled plugin config
2. Locate CommonUtilities config
3. Enable "friendly_fire_on_round_end"
4. Try and kill a teammate part way through the round

**Expected behavior**
Friendly fire to only be enabled on round end.

**Server logs**
There are none.

**Copy of current CU config section**
friendly_fire_on_round_end: false

**EXILED Version ("latest" is not a version):**
Exiled v5.1.3

**Results of `show plugins` command in console:**
Common Utilities:
    - Author: Galaxy119
    - Version: 6.0.0.0
    - Required Exiled Version: 5.0.0
    - Prefix: CommonUtilities
     - Priority: Medium

**Comment by Kayckbr** [comment]
its happening for everyone. Was going to make a issue but already are.
