### ISSUE TITLE
Friendly Fire on round end doesn't seem to disable

### ISSUE THREAD

**Issue by MisterMayoNL** [Exiled-Team/Common-Utils#97]
Tested on Exiled 5.2.1 (latest version at the time of typing this) and without any other plugins enabled.

Friendly Fire stays on after the round end, so I have to manually disable it again next round.

**Comment by Nathan43615** [comment]
I can confirm this is also happening on my server, the only way to fix is to manually disable after every round.

**Comment by joker-119** [comment]
This is an exiled/sl issue not the plugin
